In [1]:
# import library 
import numpy as np

## Array

In [6]:
# membuat array
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print('array 1 dimensi : \n',a,'\n')
print('array 2 dimensi : \n',b,'\n')
print('array 3 dimensi : \n',c,'\n')

array 1 dimensi : 
 [1 2 3] 

array 2 dimensi : 
 [[1 2 3]
 [4 5 6]] 

array 3 dimensi : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [12]:
# membuat array dengan nilai 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# membuar array dengan nilai 1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
# mermbuat array dengan method arange
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# membuat array dengan method linspace
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [19]:
# mengatur type data array
np.array([1,2,3],dtype=np.int64)

array([1, 2, 3], dtype=int64)

In [24]:
# cek dimensi array
myVar = np.array([1,2,3])
myVar2 = np.array([[1,2,4],[2,4,6]])

print(myVar.ndim)
print(myVar2.ndim)

1
2


In [30]:
# cek jumlah elemen didalam array
myVar = np.arange(7,50)
print(myVar)
print(myVar.size)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
43


In [34]:
# cek jumlah baris dan kolom
myVar2 = np.array([[1,2,4],[2,4,6]])
print(myVar2)
print(myVar2.shape)

[[1 2 4]
 [2 4 6]]
(2, 3)


In [36]:
# mengurutkan element array
myVar = np.array([3,7,9,1,2,4,7])
np.sort(myVar)

array([1, 2, 3, 4, 7, 7, 9])

In [41]:
# menggabungkan array 1 d
conc_1 = np.array([1,2,3])
conc_2 = np.array([2,4,6])
concat = np.concatenate((conc_1,conc_2))
concat

array([1, 2, 3, 2, 4, 6])

In [42]:
# menggabungkan array 2 d
conc_1 = np.array([[1,2],[3,4]])
conc_2 = np.array([[2,4],[3,5]])
concat = np.concatenate((conc_1,conc_2))
concat

array([[1, 2],
       [3, 4],
       [2, 4],
       [3, 5]])

## Subsetting

In [43]:
data = np.arange(20)

In [44]:
data[7]

7

In [45]:
data[2:7]

array([2, 3, 4, 5, 6])

In [46]:
data[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
data[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
data[1:10:2]

array([1, 3, 5, 7, 9])

In [51]:
myVar = np.array([[1,2,3,4],[5,6,7,8]])
myVar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
myVar[0]

array([1, 2, 3, 4])

In [53]:
myVar[0][3]

4

In [54]:
myVar =  np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
myVar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
myVar[myVar > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
cek = myVar > 4
cek

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
myVar[cek]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
# Menggabungkan array secara vertikal
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.vstack((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [60]:
# menggabungkan array secara horizontal
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.hstack((x,y))
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [63]:
# mengubah bentuk array
x = np.arange(1,13)
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
# split horizontal
x = np.arange(24)
x = np.hsplit(x,4)
x

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]

In [72]:
# split vertikal 
x = np.array([[1,2],[3,4],[5,6],[7,8]])
np.vsplit(x,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [73]:
# copy
a = np.arange(11)
b_copy = a.copy()
b_slice = a[2:7]

In [74]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
b_slice

array([2, 3, 4, 5, 6])

In [76]:
b_slice[3]= 78

In [77]:
b_slice

array([ 2,  3,  4, 78,  6])

In [78]:
a

array([ 0,  1,  2,  3,  4, 78,  6,  7,  8,  9, 10])

In [79]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Operations

In [86]:
a = np.array([2,6])
b = np.array([3,9])

In [87]:
a + b

array([ 5, 15])

In [88]:
b - a

array([1, 3])

In [89]:
a * b

array([ 6, 54])

In [91]:
a / b

array([0.66666667, 0.66666667])

In [92]:
myVar = np.array([[2,5,1,7],[2,5,9,3]])

In [98]:
myVar

array([[2, 5, 1, 7],
       [2, 5, 9, 3]])

In [95]:
myVar.shape

(2, 4)

In [96]:
myVar.min()

1

In [97]:
myVar.min(axis=0)

array([2, 5, 1, 3])

In [99]:
myVar.min(axis=1)

array([1, 2])

In [100]:
myVar.max(axis=0)

array([2, 5, 9, 7])

In [101]:
myVar.max(axis=1)

array([7, 9])

In [103]:
myVar.sum(axis=0)

array([ 4, 10, 10, 10])

In [104]:
myVar.sum(axis=1)

array([15, 19])