In [1]:
# import library 
import numpy as np

# Array

In [2]:
# membuat array
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print('array 1 dimensi : \n',a,'\n')
print('array 2 dimensi : \n',b,'\n')
print('array 3 dimensi : \n',c,'\n')

array 1 dimensi : 
 [1 2 3] 

array 2 dimensi : 
 [[1 2 3]
 [4 5 6]] 

array 3 dimensi : 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 



In [3]:
# membuat array dengan nilai 0
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# membuar array dengan nilai 1
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# mermbuat array dengan method arange
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
# membuat array dengan method linspace
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
# mengatur type data array
np.array([1,2,3],dtype=np.int64)

array([1, 2, 3], dtype=int64)

In [8]:
# cek dimensi array
myVar = np.array([1,2,3])
myVar2 = np.array([[1,2,4],[2,4,6]])

print(myVar.ndim)
print(myVar2.ndim)

1
2


In [9]:
# cek type data array
myVar.dtype

dtype('int32')

In [10]:
# cek jumlah elemen didalam array
myVar = np.arange(7,50)
print(myVar)
print(myVar.size)

[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30
 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
43


In [11]:
# cek jumlah baris dan kolom
myVar2 = np.array([[1,2,4],[2,4,6]])
print(myVar2)
print(myVar2.shape)

[[1 2 4]
 [2 4 6]]
(2, 3)


In [12]:
# mengurutkan element array
myVar = np.array([3,7,9,1,2,4,7])
np.sort(myVar)

array([1, 2, 3, 4, 7, 7, 9])

In [13]:
# menggabungkan array 1 d
conc_1 = np.array([1,2,3])
conc_2 = np.array([2,4,6])
concat = np.concatenate((conc_1,conc_2))
concat

array([1, 2, 3, 2, 4, 6])

In [14]:
# menggabungkan array 2 d
conc_1 = np.array([[1,2],[3,4]])
conc_2 = np.array([[2,4],[3,5]])
concat = np.concatenate((conc_1,conc_2))
concat

array([[1, 2],
       [3, 4],
       [2, 4],
       [3, 5]])

### Subsetting

In [15]:
data = np.arange(20)

In [16]:
data[7]

7

In [17]:
data[2:7]

array([2, 3, 4, 5, 6])

In [18]:
data[9:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
data[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
data[1:10:2]

array([1, 3, 5, 7, 9])

In [21]:
myVar = np.array([[1,2,3,4],[5,6,7,8]])
myVar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
myVar[0]

array([1, 2, 3, 4])

In [23]:
myVar[0][3]

4

In [24]:
myVar =  np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
myVar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
myVar[myVar > 4]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
cek = myVar > 4
cek

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
myVar[cek]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
# Menggabungkan array secara vertikal
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.vstack((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [29]:
# menggabungkan array secara horizontal
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

z = np.hstack((x,y))
z

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [30]:
# mengubah bentuk array
x = np.arange(1,13)
x.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# split horizontal
x = np.arange(24)
x = np.hsplit(x,4)
x

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]

In [32]:
# split vertikal 
x = np.array([[1,2],[3,4],[5,6],[7,8]])
np.vsplit(x,2)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [33]:
# copy
a = np.arange(11)
b_copy = a.copy()
b_slice = a[2:7]

In [34]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
b_slice

array([2, 3, 4, 5, 6])

In [36]:
b_slice[3]= 78

In [37]:
b_slice

array([ 2,  3,  4, 78,  6])

In [38]:
a

array([ 0,  1,  2,  3,  4, 78,  6,  7,  8,  9, 10])

In [39]:
b_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Operations

In [40]:
a = np.array([2,6])
b = np.array([3,9])

In [41]:
a + b

array([ 5, 15])

In [42]:
b - a

array([1, 3])

In [43]:
a * b

array([ 6, 54])

In [44]:
a / b

array([0.66666667, 0.66666667])

In [45]:
myVar = np.array([[2,5,1,7],[2,5,9,3]])

In [46]:
myVar

array([[2, 5, 1, 7],
       [2, 5, 9, 3]])

In [47]:
myVar.shape

(2, 4)

In [48]:
myVar.min()

1

In [49]:
myVar.min(axis=0)

array([2, 5, 1, 3])

In [50]:
myVar.min(axis=1)

array([1, 2])

In [51]:
myVar.max(axis=0)

array([2, 5, 9, 7])

In [52]:
myVar.max(axis=1)

array([7, 9])

In [53]:
myVar.sum(axis=0)

array([ 4, 10, 10, 10])

In [54]:
myVar.sum(axis=1)

array([15, 19])

# Dictionary

In [55]:
my_dict = {
    'Alex' : 5,
    'Ben' : 10,
    'Carly' : 12,
    'Daniele' : 14,
    'Evan' : 5    
}

In [56]:
my_dict

{'Alex': 5, 'Ben': 10, 'Carly': 12, 'Daniele': 14, 'Evan': 5}

In [57]:
my_dict['Alex']

5

In [58]:
my_dict['dwi'] = 68

In [59]:
my_dict

{'Alex': 5, 'Ben': 10, 'Carly': 12, 'Daniele': 14, 'Evan': 5, 'dwi': 68}

In [60]:
my_dict.pop('dwi')

68

In [61]:
my_dict

{'Alex': 5, 'Ben': 10, 'Carly': 12, 'Daniele': 14, 'Evan': 5}

In [62]:
my_dict.popitem()

('Evan', 5)

In [63]:
my_dict

{'Alex': 5, 'Ben': 10, 'Carly': 12, 'Daniele': 14}

In [64]:
del my_dict['Alex']

In [65]:
my_dict

{'Ben': 10, 'Carly': 12, 'Daniele': 14}

# Pandas

In [66]:
# import library
import pandas as pd

In [67]:
theList = [100,200,300]
theArray = np.array([100,200,300])
theLabel = ['Pertama','Kedua','Ketiga']
theDict = {"Pertama" : 100, "kedua": 200, "ketiga":300}

theListSeries =  pd.Series(data=theList, index=theLabel)
theArraySeries = pd.Series(theArray, theLabel)
theDictSeries = pd.Series(theDict)

In [68]:
print(theListSeries)

Pertama    100
Kedua      200
Ketiga     300
dtype: int64


In [69]:
print(theArraySeries)

Pertama    100
Kedua      200
Ketiga     300
dtype: int32


In [70]:
print(theDictSeries)

Pertama    100
kedua      200
ketiga     300
dtype: int64


In [71]:
seriesHarga = pd.Series([1000,2000,3000,4000], index=['Sepatu','Tas','Baju','Jaket'])
seriesHarga

Sepatu    1000
Tas       2000
Baju      3000
Jaket     4000
dtype: int64

In [72]:
# membuat dataframe dari dict
pd.DataFrame({'dwi':79,'agung':34,'wahyu':45},index=[1,2,3])

dwi  agung  wahyu
1   79     34     45
2   79     34     45
3   79     34     45

In [73]:
# membuat dataframe dengan list
pd.DataFrame([100,200,300])

0
0  100
1  200
2  300

In [74]:
dictTinggi = {'dwi':180,'wahyu':175, 'ary':168}
seriesTinggi = pd.Series(dictTinggi)
dataMahasiswa = pd.DataFrame(seriesTinggi, columns=['TinggiBadan'])
dataMahasiswa

TinggiBadan
dwi            180
wahyu          175
ary            168

In [75]:
dataMahasiswa['BeratBadan'] = [80,55,75]
dataMahasiswa['Universitas'] = ['ITB', 'UI', 'UB']
dataMahasiswa['IPK'] = [3.4, 4.0, 3.2]
dataMahasiswa['Umur'] = [19, 20, 19]
dataMahasiswa

TinggiBadan  BeratBadan Universitas  IPK  Umur
dwi            180          80         ITB  3.4    19
wahyu          175          55          UI  4.0    20
ary            168          75          UB  3.2    19

In [76]:
# membuat column baru
dataMahasiswa['IMT'] = dataMahasiswa['BeratBadan']/((dataMahasiswa['TinggiBadan']/10)*dataMahasiswa['TinggiBadan'])
dataMahasiswa

TinggiBadan  BeratBadan Universitas  IPK  Umur       IMT
dwi            180          80         ITB  3.4    19  0.024691
wahyu          175          55          UI  4.0    20  0.017959
ary            168          75          UB  3.2    19  0.026573

In [77]:
# hapus column secara sementara
print(dataMahasiswa.drop('IMT',axis=1))
print('-'*60)
print(dataMahasiswa)

       TinggiBadan  BeratBadan Universitas  IPK  Umur
dwi            180          80         ITB  3.4    19
wahyu          175          55          UI  4.0    20
ary            168          75          UB  3.2    19
------------------------------------------------------------
       TinggiBadan  BeratBadan Universitas  IPK  Umur       IMT
dwi            180          80         ITB  3.4    19  0.024691
wahyu          175          55          UI  4.0    20  0.017959
ary            168          75          UB  3.2    19  0.026573


In [78]:
# hapus column secara permanen
dataMahasiswa.drop('IMT',axis=1, inplace=True)
dataMahasiswa

TinggiBadan  BeratBadan Universitas  IPK  Umur
dwi            180          80         ITB  3.4    19
wahyu          175          55          UI  4.0    20
ary            168          75          UB  3.2    19

In [79]:
dataMahasiswa[(dataMahasiswa['IPK']>3)&(dataMahasiswa['Umur']<20)]

TinggiBadan  BeratBadan Universitas  IPK  Umur
dwi          180          80         ITB  3.4    19
ary          168          75          UB  3.2    19

In [80]:
dataMahasiswa[dataMahasiswa['Universitas']=='UI']

TinggiBadan  BeratBadan Universitas  IPK  Umur
wahyu          175          55          UI  4.0    20

In [81]:
print(dataMahasiswa['Universitas'])
print('-'*40)

print(dataMahasiswa[['Universitas','IPK']])
print('-'*40)

print(dataMahasiswa.TinggiBadan)

dwi      ITB
wahyu     UI
ary       UB
Name: Universitas, dtype: object
----------------------------------------
      Universitas  IPK
dwi           ITB  3.4
wahyu          UI  4.0
ary            UB  3.2
----------------------------------------
dwi      180
wahyu    175
ary      168
Name: TinggiBadan, dtype: int64


In [82]:
dataMahasiswa.loc['dwi']

TinggiBadan    180
BeratBadan      80
Universitas    ITB
IPK            3.4
Umur            19
Name: dwi, dtype: object

In [83]:
dataMahasiswa.loc['dwi']

TinggiBadan    180
BeratBadan      80
Universitas    ITB
IPK            3.4
Umur            19
Name: dwi, dtype: object

In [84]:
dataMahasiswa.iloc[:2]

TinggiBadan  BeratBadan Universitas  IPK  Umur
dwi            180          80         ITB  3.4    19
wahyu          175          55          UI  4.0    20

In [85]:
dataMahasiswa.loc['dwi','TinggiBadan']

180

In [86]:
dataMahasiswa.loc[['dwi','ary'],['TinggiBadan','BeratBadan']]

TinggiBadan  BeratBadan
dwi          180          80
ary          168          75

In [87]:
# read file csv
titanic = pd.read_csv('titanic_train.csv')
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [88]:
nmale = len(titanic[titanic['Sex']=='male'])
nfemale = len(titanic[titanic['Sex']=='female'])
print(nmale,nfemale)

577 314


In [89]:
maleSurvived = len(titanic[(titanic['Sex']=="male")&(titanic['Survived']==1)])
maleNotSurvived = len(titanic[(titanic['Sex']=="male")&(titanic['Survived']==0)])
femaleSurvived = len(titanic[(titanic['Sex']=="female")&(titanic['Survived']==1)])
femaleNotSurvived = len(titanic[(titanic['Sex']=="female")&(titanic['Survived']==0)])

In [90]:
print('Jumlah pria yang selamat :', maleSurvived)
print('Jumlah pria yang tidak selamat :', maleNotSurvived)
print('Jumlah wanita yang selamat :', femaleSurvived)
print('Jumlah wanita yang tidak selamat :', femaleNotSurvived)

Jumlah pria yang selamat : 109
Jumlah pria yang tidak selamat : 468
Jumlah wanita yang selamat : 233
Jumlah wanita yang tidak selamat : 81


In [91]:
titanic.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Dictionary & Pandas

In [113]:
grade = {
    'Alex' : 200,
    'Acoy' : 150,
    'Acil' : 140
}

In [114]:
grade

{'Alex': 200, 'Acoy': 150, 'Acil': 140}

In [115]:
grade['Alex']

200

In [116]:
grade.get('Alex')

200

In [117]:
grade.keys()

dict_keys(['Alex', 'Acoy', 'Acil'])

In [118]:
grade.values()

dict_values([200, 150, 140])

In [119]:
for i in grade:
    print(i)

Alex
Acoy
Acil


In [120]:
for i in grade:
    print(grade[i])

200
150
140


In [121]:
grade

{'Alex': 200, 'Acoy': 150, 'Acil': 140}

In [122]:
grade['Alex'] = 450

In [123]:
grade

{'Alex': 450, 'Acoy': 150, 'Acil': 140}

In [124]:
grade['Dwi'] = 500

In [125]:
grade

{'Alex': 450, 'Acoy': 150, 'Acil': 140, 'Dwi': 500}

In [126]:
grade.pop('Acoy')

150

In [127]:
grade

{'Alex': 450, 'Acil': 140, 'Dwi': 500}

In [128]:
grade.popitem()

('Dwi', 500)

In [129]:
grade

{'Alex': 450, 'Acil': 140}

In [130]:
del grade['Alex']

In [131]:
grade

{'Acil': 140}

In [132]:
myfamily = {
    'child' : {
        'name' : 'dwi saputra',
        'year' : 1997
    },
    'child2' : {
        'name' : 'yulia novita',
        'year' : 2002
    }
}

In [133]:
myfamily

{'child': {'name': 'dwi saputra', 'year': 1997},
 'child2': {'name': 'yulia novita', 'year': 2002}}

In [134]:
myfamily['child']

{'name': 'dwi saputra', 'year': 1997}

In [135]:
myfamily['child']['year']

1997

In [142]:
myfamily['child2'] = {
    'name' : 'Yulia Novita',
    'year' : 2002
}

In [143]:
myfamily

{'child': {'name': 'dwi saputra', 'year': 1997},
 'child2': {'name': 'Yulia Novita', 'year': 2002},
 'child3': {'name': 'Gagah Andika Kusuma Wijaya', 'year': 2012}}

In [144]:
myfamily['child3'] = {
    'name' : 'Gagah Andika Kusuma Wijaya',
    'year' : 2012
}

In [145]:
myfamily

{'child': {'name': 'dwi saputra', 'year': 1997},
 'child2': {'name': 'Yulia Novita', 'year': 2002},
 'child3': {'name': 'Gagah Andika Kusuma Wijaya', 'year': 2012}}

In [146]:
myfamily.popitem()

('child3', {'name': 'Gagah Andika Kusuma Wijaya', 'year': 2012})

In [147]:
myfamily.pop('child')

{'name': 'dwi saputra', 'year': 1997}

In [148]:
myfamily

{'child2': {'name': 'Yulia Novita', 'year': 2002}}

In [149]:
del myfamily['child2']

In [150]:
myfamily

{}

In [151]:
myfamily = {
    'child' : {
        'name' : 'dwi saputra',
        'year' : 1997
    },
    'child2' : {
        'name' : 'yulia novita',
        'year' : 2002
    },
    'child3' : {
        'name' : 'Gagah Andika Kusuma Wijaya',
        'year' : 2012
    }
}

In [152]:
import pandas as pd
import numpy as np
import os

In [153]:
os.getcwd()

'C:\\Users\\Dwi Saputra\\Documents\\SHIFT ACADEMY\\Data Manipulation'

In [154]:
product = pd.read_csv('product_list.csv',delimiter=';')
product

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000
3      987      macbook_pro   5000
4     9876        sony_vaio   1500
5     8765       hp_spectre   2300
6     7654          hp_envy   2600

In [155]:
product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   prod_id    7 non-null      int64 
 1   prod_name  7 non-null      object
 2   price      7 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 296.0+ bytes


In [156]:
product['prod_name']

0      dell_latitude
1    lenovo_thinkpad
2        macbook_air
3        macbook_pro
4          sony_vaio
5         hp_spectre
6            hp_envy
Name: prod_name, dtype: object

In [157]:
product.head()

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000
3      987      macbook_pro   5000
4     9876        sony_vaio   1500

In [158]:
product.tail()

prod_id    prod_name  price
2     7890  macbook_air   4000
3      987  macbook_pro   5000
4     9876    sony_vaio   1500
5     8765   hp_spectre   2300
6     7654      hp_envy   2600

In [159]:
product[0:2]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800

In [160]:
product['prod_name'][:3]

0      dell_latitude
1    lenovo_thinkpad
2        macbook_air
Name: prod_name, dtype: object

In [162]:
product[['prod_name'][:3]]

prod_name
0    dell_latitude
1  lenovo_thinkpad
2      macbook_air
3      macbook_pro
4        sony_vaio
5       hp_spectre
6          hp_envy

In [165]:
product[['prod_name','price']][:3]

prod_name  price
0    dell_latitude   1900
1  lenovo_thinkpad   1800
2      macbook_air   4000

In [166]:
product[product['prod_name']=='dell_latitude']

prod_id      prod_name  price
0     1234  dell_latitude   1900

In [167]:
product[product['price']>3000]

prod_id    prod_name  price
2     7890  macbook_air   4000
3      987  macbook_pro   5000

In [168]:
product[product['prod_name'].apply(lambda x : str(x)[:2]=='hp')]

prod_id   prod_name  price
5     8765  hp_spectre   2300
6     7654     hp_envy   2600

In [169]:
product[(product['prod_name'].apply(lambda x : str(x)[:2] == 'hp')) & (product['price']>2500) ]

prod_id prod_name  price
6     7654   hp_envy   2600

In [171]:
product[(product['prod_name'].apply(lambda x : str(x)[:2]=='hp')) | (product['price']>2500)]

prod_id    prod_name  price
2     7890  macbook_air   4000
3      987  macbook_pro   5000
5     8765   hp_spectre   2300
6     7654      hp_envy   2600

In [172]:
product.loc[:3]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000
3      987      macbook_pro   5000

In [173]:
product.loc[:3,'price']

0    1900
1    1800
2    4000
3    5000
Name: price, dtype: int64

In [174]:
product.loc[:3,'prod_id':'price']

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000
3      987      macbook_pro   5000

In [175]:
product.loc[:3,['prod_id']]

prod_id
0     1234
1     3456
2     7890
3      987

In [176]:
product.loc[:3,['prod_id','price']]

prod_id  price
0     1234   1900
1     3456   1800
2     7890   4000
3      987   5000

In [177]:
product.iloc[:3]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000

In [178]:
product.iloc[:3,0:3]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000

In [180]:
product.iloc[:3,[1]]

prod_name
0    dell_latitude
1  lenovo_thinkpad
2      macbook_air

In [179]:
product.iloc[:3,[1,2]]

prod_name  price
0    dell_latitude   1900
1  lenovo_thinkpad   1800
2      macbook_air   4000

Perbedaan loc & iloc

In [181]:
product.loc[0:3]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000
3      987      macbook_pro   5000

In [182]:
product.iloc[0:3]

prod_id        prod_name  price
0     1234    dell_latitude   1900
1     3456  lenovo_thinkpad   1800
2     7890      macbook_air   4000

In [183]:
product.loc[:,'prod_name']

0      dell_latitude
1    lenovo_thinkpad
2        macbook_air
3        macbook_pro
4          sony_vaio
5         hp_spectre
6            hp_envy
Name: prod_name, dtype: object

In [185]:
# iloc tidak dapat menampilkan column tertentu
product.iloc[:,'prod_name']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types